### ISSUE TITLE
Remap <Leader>h

### ISSUE THREAD

**Issue by you-n-g** [pevhall/simple_highlighting#1]
Hi, 
This plugin is great to me. 
Thanks your efforts.

How could I unbind such mapping and create my own mapping?
```
nmap <Leader>h :<C-U> exe "call HighlightAdd(".v:count.",'\\<".expand('<cword>')."\\>')"<CR>
```
I've tried `nunmap <Leader>h` in `init.vim` but with no luck

Thanks

**Comment by pevhall** [comment]
Thanks for your interest you-n-g. I've just pushed the change you require so please do a pull and then place the following in your init.vimfile:

    nmap <Leader>h <Plug>HighlightWordUnderCursor
    
But replace \<Leader\>h with your preferred mapping. This will use the preferred mapping instead of the default \<Leader\>h. Leaving you to set <Leader>h to whatever you prefer.

I'll leave the issue open until you have confirmed it works or until I update the documentation tomorrow.

**Comment by you-n-g** [comment]
Thanks your quick response! The new code works very well!!

But I found another issue.

It conflicts with the feature `Highlight symbol under cursor on CursorHold` of [coc.nvim](https://github.com/neoclide/coc.nvim). 

When I set   `autocmd CursorHold * silent call CocActionAsync('highlight')` in my  neovim `init.vim`
`simple_highlighting` will be overritten by the coc.nvim

**Comment by pevhall** [comment]
Going to bed now I'll try this out tomorrow

**Comment by pevhall** [comment]
Hi you-n-g,

Please do a pull and tell me if you now see your desired behavior or not.

Thanks

**Comment by you-n-g** [comment]
It's great!
It works very vell now!

I found anther issue when updating it with [vim-plug](https://github.com/junegunn/vim-plug)
- Such error info appears after I run neither `:PlugUpdate simple_highlighting` or `:PlugUpdate` . But it doesn't affact the usage of the nice plugin.


![image](https://user-images.githubusercontent.com/465606/94087471-6e4b1d80-fe40-11ea-9c53-493388e3c0d9.png)

**Comment by pevhall** [comment]
Thanks you-n-g,

It appears to have source the plugin twice.

This is the only vim script I have written and I haven't noticed an issue with the package manager I'm using (minpac)

However vim-plug is the most popular package so I'd like to get it working nicely with it. I could add a h guard pattern to prevent it from getting sourced twice. But I think there is probably a better way. I'm probably missing a way to unload the script before it reloads the updated one (something minpac doesn't do) I'll have to do some research on this one.

Thanks again for your interest and helping me check the script.

**Comment by pevhall** [comment]
Moved the ":PulgUpdate loading the pulgin twice" into it's own issue.

Original issue this ticket reference has been resolved
