### ISSUE TITLE
Same word in upper format and lower format conflicts

### ISSUE THREAD

**Issue by you-n-g** [pevhall/simple_highlighting#5]
Hi

I've got a text like this
```
asdf
ASDF
```
I found that I can't highlight both `asdf` and `ASDF`. It seems that they are conflicted.

Thanks

**Comment by pevhall** [comment]
Hi you-n-g,

Thanks for that. I hadn't tested it with the 
`set ignorecase`
option on before.

When I did test it with this option I was able to confirm the problem. The resolution I have made is all string matches will (or should be) case sensitive. Hence even if you are running with ignorecase on simple_highligting will perform case sensitive matching (unless you use regular expressions).

Please try the update and see if it fixers the problem for you.

Thanks

**Comment by pevhall** [comment]
Let me know if this works and I'll close the ticket

**Comment by you-n-g** [comment]
@pevhall  It works now!!
Thanks so much!
