### ISSUE TITLE
Do this plugin provides any method to list all the highlighted items?

### ISSUE THREAD

**Issue by you-n-g** [pevhall/simple_highlighting#6]
Sometimes we want to check what words and colors are already used,  and then highlight a new words with a new color.
But it is hard to remember what has already been highlighted.

Do this plugin provides any method to list all the highlighted items?

My current workaround is to save the current highlight schema which `:Hw` and then check the file. But is is not that convenient.

Thanks :)

**Comment by pevhall** [comment]
Hi you-n-g,

Yes i can create a new function to open a new buffer contain the contents that `:Hw` would write. Is that what you are after?

**Comment by pevhall** [comment]
Hi you-n-g, I just created a quick function which `:Hwb` which opens a new split (`:new`) and populates it with the current search patter (what `:Hw` would write).

Is that what you where after?

**Comment by you-n-g** [comment]
@pevhall  Thanks so much.
It is much better than my workaround!
